### ISSUE TITLE
资讯一些小细节

### ISSUE THREAD

**Issue by CainLuo** [cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580#1]
请问一下Z390 Aorus Pro WiFi可以自行更换WiFi吗? 还有就是把CPU换成9900K, 显卡换成Vega56这个EFI还可以用么?

**Comment by cheneyveron** [comment]
1. 更换WiFi还未试过，但是在Tonymacx86上的一个老哥将他的 Asrock Z390-I ac 的WiFi蓝牙模块换了，并且成功了，如果有兴趣的话，见[这里](https://www.tonymacx86.com/threads/success-asrock-z390-phantom-gaming-itx-tb3-igpu-mojave-sff-build.277418/)
2. CPU换成9900k后，如果还想用核显，请自行修改Device部分。
3. 显卡换成Vega56后可以原生硬解，建议直接BIOS中关闭核显。如果直接关闭核显，那么就可以直接用我的EFI。
