### ISSUE TITLE
USB安装盘无法启动

### ISSUE THREAD

**Issue by microzhang715** [cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580#10]
制作完成USB安装盘后
1、负责本项目EFI到EFI分区
2、clover配置中屏蔽掉acpi---nv-disable的patch
3、启动引导

直接黑屏断电后重启，无法引导使用

**Comment by cheneyveron** [comment]
这是OpenCore，不是Clover哦。
是否事先调整了BIOS设置，以及关闭了CFG-Lock？

**Comment by microzhang715** [comment]
1、确实使用的是OpenCore，使用主板和楼主一样
2、后来参考https://github.com/blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore

这位大佬的配置成功安装
3、最终方案：使用本仓库中的所有kext驱动文件 + 步骤2中仓库的ACPI几config.plist文件成功安装切使用

在此，感谢楼主的分享，楼主有时间可以升级到最新版本的OpenCore，OpenCore确实引导速度快非常多
