### ISSUE TITLE
请教大佬一个关于 AppleACPIPlatform  的问题。

### ISSUE THREAD

**Issue by crazyhulk** [cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580#13]
你好，我的主板是 ASRock EPC621D8A，在之前是正常的，但是 BIOS 默认没有解锁 CFG Lock， 然后我在网上找了一个解锁的版本刷了进去，在 win 下看到确实解锁了 BIOS （rweverything），但是导致我无法启动系统。
OpenCore 跟 Clover 都卡在
![02a96c26d64d347092ec4a60ca11542](https://user-images.githubusercontent.com/13976375/85721187-b82e4580-b723-11ea-9a3b-dfcc3ff81c23.jpg)

如果 Clover 开启 "Patch APIC" 就会得到以下错误。
![559239c2fe35fa43304fdb9c37dcaf1](https://user-images.githubusercontent.com/13976375/85721408-e9a71100-b723-11ea-8bcb-7573721897c3.jpg)

找到了您在  [这里](https://www.insanelymac.com/forum/topic/326200-new-possibilities-for-x79-appleacpiplatform-panic/) 的帖子，但是貌似 FixHeaders 并不起作用。
试了试你发布的 config （x79）那个，如下
![Screen Shot 2020-06-25 at 10 28 41 PM](https://user-images.githubusercontent.com/13976375/85739317-43fb9e00-b733-11ea-98ae-3d90b438a5c3.png)

先行感谢！

**Comment by cheneyveron** [comment]
猜测是某个ssdt加载时出现问题，依次drop ssdt试试？

**Comment by crazyhulk** [comment]
@cheneyveron 如果不drop APIC.aml 或者不 Patch APIC 不报错，否则会卡住（第一张图）。
drop APIC.aml 会导致 AppleACPIPlatformExpert::start failed.

`AAFT.aml                 HEST.aml                 SLIT.aml
APIC.aml                 HPET.aml                 SPMI.aml
ASF!.aml                 MCFG.aml                 SRAT.aml
BERT.aml                 MIGT.aml                 SSDT-0-ADDRXLAT.aml
BGRT.aml                 MSCT.aml                 SSDT-1-SSDT  PM.aml
DMAR.aml                 OEM1.aml                 SSDT-2-A M I.aml
DSDT.aml                 OEM2.aml                 SVOS.aml
DumpLog.txt              OEM4.aml                 VFCT.aml
EINJ.aml                 PCAT.aml                 WDDT.aml
ERST.aml                 RASF.aml                 WSMT.aml
FACP.aml                 RSDP.aml                 XSDT.aml
FACS.aml                 RSDT-FACP.aml   
FIDT.aml                 RSDT-FACS.aml
FPDT.aml                 RSDT.aml`

除了 dsdt 都要试试么？

**Comment by cheneyveron** [comment]
除了dsdt和apic可以全drop试试

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: TC <notifications@github.com>
发送时间: Friday, June 26, 2020 8:29:56 AM
收件人: cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580 <hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580@noreply.github.com>
抄送: Cheney Veron <cheneyveron@live.cn>; Mention <mention@noreply.github.com>
主题: Re: [cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580] 请教大佬一个关于 AppleACPIPlatform 的问题。 (#13)


@cheneyveron<https://github.com/cheneyveron> 如果不drop APIC.aml 不报错，否则会卡住（第一张图）。

AAFT.aml HEST.aml SLIT.aml APIC.aml HPET.aml SPMI.aml ASF!.aml MCFG.aml SRAT.aml BERT.aml MIGT.aml SSDT-0-ADDRXLAT.aml BGRT.aml MSCT.aml SSDT-1-SSDT PM.aml DMAR.aml OEM1.aml SSDT-2-A M I.aml DSDT.aml OEM2.aml SVOS.aml DumpLog.txt OEM4.aml VFCT.aml EINJ.aml PCAT.aml WDDT.aml ERST.aml RASF.aml WSMT.aml FACP.aml RSDP.aml XSDT.aml FACS.aml RSDT-FACP.aml FIDT.aml RSDT-FACS.aml FPDT.aml RSDT.aml

出了 dsdt 都要试试么？

―

**Comment by crazyhulk** [comment]
@cheneyveron 

drop 的情况下会导致如下错误。

![Screen Shot 2020-06-26 at 10 57 42 AM](https://user-images.githubusercontent.com/13976375/85815777-eea7a700-b79b-11ea-97d1-ee5d07e532a1.png)

如果我强行加载更新bios之前的dsdt是可以跳过的（卡IOConsoleUser.....)，但是跟没跟新前一样无法进系统（更新前不需要dsdt，如果强行加载就进不去）

**Comment by cheneyveron** [comment]
我的微信是我的GitHub用户名，也许可以详谈？

**Comment by cheneyveron** [comment]
最终通过将旧BIOS中dsdt中的Processor替换进新dsdt中解决问题。
