### ISSUE TITLE
再次请教关于升级问题

### ISSUE THREAD

**Issue by JeremyXING** [cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580#16]
大佬你好，相同主板、CPU、显卡，去年用了您的配置安装了10.14，完美运行至今十分感谢，如今发现您这里已经升级到了10.15并且换用了opencore，想请教一下，如果我从10.14升级到10.15是否直接系统里升级并替换efi就好？需要进行其他的操作吗？

**Comment by cheneyveron** [comment]
建议先替换efi再升级哦。
替换efi后，建议检查一遍config.plist，比如generic部分等

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: JeremyXING <notifications@github.com>
发送时间: Monday, September 7, 2020 7:41:02 PM
收件人: cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580 <hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580] 再次请教关于升级问题 (#16)


大佬你好，相同主板、CPU、显卡，去年用了您的配置安装了10.14，完美运行至今十分感谢，如今发现您这里已经升级到了10.15并且换用了opencore，想请教一下，如果我从10.14升级到10.15是否直接系统里升级并替换efi就好？需要进行其他的操作吗？

―

**Comment by JeremyXING** [comment]
好的 十分感谢回复～我先尝试一下～
