### ISSUE TITLE
请教一些小问题

### ISSUE THREAD

**Issue by JeremyXING** [cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580#2]
老铁你好，非常感谢你的efi。
非常缘分，同款主版、cpu、同 rtx2080 + rx580，直接用了你的efi非常棒。但是我在黑苹果下摸了下N卡发现非常的烫，请问是哪里需要修改下吗？
而且进bios 只能n卡输出，进系统才换成a卡，bios设置输出也没啥用，请问有啥好的办法吗？

**Comment by cheneyveron** [comment]
我用功率计测试了一下，即便是屏蔽了N卡，功率仍然会高100w的样子，也会烫，说明操作系统不调用的时候显卡实际上也会自己运行一些idle程序。

我感觉bios只n卡输出是bios的一个bug，建议把显示器同时连接580和2080，打算进bios的话就在显示器上切换到2080连接的接口

**Comment by JeremyXING** [comment]
好吧。。看样也只能这样处理了。。因为偶尔可能会切ubuntu 跑深度学习只能插着n卡，又担心这么烫长时间会损坏显卡，目前也是开机切输出信号解决的，稍微麻烦点倒也还好。。
Anyway，感谢回答～
