### ISSUE TITLE
求教BCM943602CS蓝牙无法使用

### ISSUE THREAD

**Issue by zijianwang90** [cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580#9]
您好，非常感谢您的efi，我的同款无wifi的主板已经安装基本成功。
现在还有个小问题就是和您之前买的同款网卡BCM943602CS蓝牙无法被驱动。在windows下可以正常使用，说明网卡应该是没问题。
请问在这个问题上有解决办法或者思路吗？

**Comment by cheneyveron** [comment]
蓝牙用的是usb端口，检查一下usb端口是否都启动啦？

在 2020年2月24日，下午10:31，Zijian Wang <notifications@github.com> 写道：

﻿

您好，非常感谢您的efi，我的同款无wifi的主板已经安装基本成功。
现在还有个小问题就是和您之前买的同款网卡BCM943602CS蓝牙无法被驱动。在windows下可以正常使用，说明网卡应该是没问题。
请问在这个问题上有解决办法或者思路吗？

**Comment by zijianwang90** [comment]
好的，请问这里有什么思路吗？例如该如何检查？我尝试了使用博通四件套的kext和usbinjectall的kext都无果。

**Comment by zijianwang90** [comment]
后来发现问题的所在了，那就是定制usb没有定制HS11和HS12，分别是主板上面的两个usb端口，定制上以后就有蓝牙的，但问题又来了，有了蓝牙后又睡眠秒醒了。。应该是蓝牙的锅。。
不过问题算是解决了，还是想问下您选的是哪款usb蓝牙，我想试试 @cheneyveron

**Comment by cheneyveron** [comment]
我的机箱上没USB2的接口，也没用PCIE蓝牙，所以索性就没驱动USB2.0的接口。
当时买的是这个：
https://item.taobao.com/item.htm?id=565562245254
只支持蓝牙4.0
